server:
  port: 8098

spring:
  main:
    web-application-type: SERVLET

  datasource:
    url: jdbc:postgresql://127.0.0.1:5432/spring-boot-amigoscode
    username: postgres
    password: postgres
    driverClassName: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
    show-sql: true